include:
  - local: 'infra/environments/*.yml'


variables:
  RUNNER_TAGS: dev
  TF_VERSION: "1.3.6"
  TF_CLOUD_CREDENTIALS: |
    credentials "app.terraform.io" {
      token = "${TF_CLOUD_TEAM_TOKEN}"
    }


stages:
  - validate
  - plan
  - apply


image:
  name: hashicorp/terraform:${TF_VERSION}
  entrypoint: [""]


.terraform:
  variables:
    PLAN: ${TF_WORKSPACE}.tfplan
    PLAN_JSON: ${TF_WORKSPACE}-plan.json
    OUTPUT: ${TF_WORKSPACE}-out.json
  before_script:
    - apk add --update --no-cache jq aws-cli gettext bash
    - alias convert_report="jq -r '([.resource_changes[]?.change.actions?]|flatten)|{\"create\":(map(select(.==\"create\"))|length),\"update\":(map(select(.==\"update\"))|length),\"delete\":(map(select(.==\"delete\"))|length)}'"
    - echo "${TF_CLOUD_CREDENTIALS}" > "${HOME}/.terraformrc"
    - terraform --version
    - terraform init -upgrade
    - terraform workspace list
  rules:
    - changes: 
        - ./**/*
    - if: $CI_PIPELINE_SOURCE == "web"
  cache:
    key: ${TF_WORKSPACE}-$CI_COMMIT_REF_SLUG
    paths:
      - .terraform
  tags:
    - ${RUNNER_TAGS}


.terraform:validate:
  extends: .terraform
  stage: validate
  script:
    - terraform validate


.terraform:plan:
  extends: .terraform
  stage: plan
  script:
    - terraform plan -out=$PLAN
    - terraform show --json $PLAN | convert_report > $PLAN_JSON
  artifacts:
    reports:
      terraform: ${PLAN_JSON}
    paths:
      - ${PLAN}
  resource_group: ${TF_WORKSPACE}


.terraform:apply:
  extends: .terraform
  stage: apply
  script:
    - terraform apply $PLAN
    - terraform output -json >> $OUTPUT
  artifacts:
    paths:
      - $OUTPUT
  rules:
    - changes: 
        - ./**/*
      when: manual
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
      when: never
    - if: $CI_PIPELINE_SOURCE == "web"
      when: manual
  resource_group: ${TF_WORKSPACE}
  environment:
    name: ${TF_WORKSPACE}


.terraform:destroy-plan:
  extends: .terraform:plan
  script:
    - terraform plan -destroy -out=$PLAN
  when: manual


.terraform:destroy-apply:
  extends: .terraform:apply
  script:
    - terraform apply -destroy $PLAN
  when: manual
