name: todo
apps:
  frontend:
    name: frontend
    task:
      container_cpu: 256
      container_memory: 512
      container_environment:
        - name: key
          value: value
      portMappings:
        - protocol: "tcp"
          containerPort: 80
          hostPort: 80
    service:
      desired_count: 1
      deployment_minimum_healthy_percent: 50
      deployment_maximum_percent: 200
      health_check_grace_period_seconds: 60
    loadbalancer:
      container_port: 80
    autoscaling:
      max_capacity: 4
      min_capacity: 1
      memory:
        target_value: 80
        scale_in_cooldown: 300
        scale_out_cooldown: 300
      cpu:
        target_value: 80
        scale_in_cooldown: 300
        scale_out_cooldown: 300
        
  backend:
    name: backend
    task:
      container_cpu: 256
      container_memory: 512
      container_environment:
        - name: key
          value: value
      portMappings:
        - protocol: "tcp"
          containerPort: 3000
          hostPort: 3000
    service:
      desired_count: 1
      deployment_minimum_healthy_percent: 50
      deployment_maximum_percent: 200
      health_check_grace_period_seconds: 60
    loadbalancer:
      container_port: 3000
    autoscaling:
      max_capacity: 4
      min_capacity: 1
      memory:
        target_value: 80
        scale_in_cooldown: 300
        scale_out_cooldown: 300
      cpu:
        target_value: 80
        scale_in_cooldown: 300
        scale_out_cooldown: 300